name: Android CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [created]

env:
  JAVA_VERSION: 17
  NDK_VERSION: 26.1.10909125
  GRADLE_VERSION: 8.4

permissions: # Move this to root level
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
          cache: "gradle"

      - name: Setup Android SDK and NDK
        run: |
          # Install Android SDK Command-line tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip -q commandlinetools-linux-10406996_latest.zip
          mkdir -p ${ANDROID_SDK_ROOT}/cmdline-tools
          mv cmdline-tools ${ANDROID_SDK_ROOT}/cmdline-tools/latest

          # Install NDK
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;${{ env.NDK_VERSION }}"

          # Set environment variables
          echo "ANDROID_NDK_HOME=${ANDROID_SDK_ROOT}/ndk/${{ env.NDK_VERSION }}" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk/${{ env.NDK_VERSION }}" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build OpenSSL
        if: github.event_name != 'release'
        run: |
          ./gradlew -PndkPath=$ANDROID_NDK_ROOT build --stacktrace

      - name: Build and Publish OpenSSL
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          ./gradlew -PndkPath=$ANDROID_NDK_ROOT -Prelease release --stacktrace --info

      - name: Upload Artifacts
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: build/distributions/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
