# .github/workflows/release.yml
name: Release Management

on:
  push:
    branches:
      - staging    # For testing builds
      - release    # For creating releases

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          VERSION=$(grep "val portVersion =" build.gradle.kts | cut -d'"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Detected version: $VERSION"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
          local-cache: true

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: |
          ./gradlew distZip \
            -PndkPath=$ANDROID_NDK_HOME \
            -Psigning.gnupg.keyName=${{ secrets.GPG_KEY_ID }} \
            -Psigning.gnupg.passphrase=${{ secrets.GPG_PASSPHRASE }}

      - name: Generate SHA256 checksum
        run: |
          cd build/distributions
          sha256sum *.zip > SHA256SUMS
          gpg --armor --detach-sign SHA256SUMS

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/distributions/*.zip
            build/distributions/SHA256SUMS
            build/distributions/SHA256SUMS.asc

  release:
    needs: build
    if: github.ref == 'refs/heads/release'  # Only run on release branch
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.build.outputs.version }}
          name: Release v${{ needs.build.outputs.version }}
          body: |
            OpenSSL Android NDK Port v${{ needs.build.outputs.version }}

            ## Verification
            ```bash
            # Verify signature
            gpg --verify SHA256SUMS.asc SHA256SUMS

            # Verify checksum
            sha256sum -c SHA256SUMS
            ```
          draft: false
          prerelease: false
          files: |
            artifacts/*.zip
            artifacts/SHA256SUMS
            artifacts/SHA256SUMS.asc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Optional job for staging branch
  staging-verification:
    needs: build
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: artifacts

      - name: Verify build artifacts
        run: |
          echo "Build verification for version ${{ needs.build.outputs.version }} completed"
          echo "Artifacts available for testing:"
          ls -la artifacts/