name: Build NDK Ports

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  detect-projects:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Gradle Cache
        uses: actions/cache@v3
        id: gradle-cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Get all projects
        id: set-matrix
        run: |
          projects=$(./gradlew -q listProjects --no-daemon)
          echo "Found projects: $projects"
          echo "matrix={\"project\":$projects}" >> $GITHUB_OUTPUT

  build:
    needs: detect-projects
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.detect-projects.outputs.matrix)}}
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      # Cache Gradle files with same key as detect-projects
      - name: Setup Gradle Cache
        uses: actions/cache@v3
        id: gradle-cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/native
            ~/.gradle/daemon
            ~/.gradle/buildOutputCleanup
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # Cache NDK with commit-based key for better hit rates
      - name: Cache NDK
        id: ndk-cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/android-ndk-r26
          key: ndk-${{ runner.os }}-r26-${{ github.sha }}
          restore-keys: |
            ndk-${{ runner.os }}-r26-

      - name: Download Android NDK
        if: steps.ndk-cache.outputs.cache-hit != 'true'
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26-linux.zip
          unzip android-ndk-r26-linux.zip
          rm android-ndk-r26-linux.zip

      # Cache build outputs per project
      - name: Cache Build Outputs
        uses: actions/cache@v3
        id: build-cache
        with:
          path: |
            **/build
            !**/build/distributions
          key: build-${{ runner.os }}-${{ matrix.project }}-${{ hashFiles(format('{0}/**/*.gradle*', matrix.project)) }}
          restore-keys: |
            build-${{ runner.os }}-${{ matrix.project }}-

      # Debug step to verify cache contents
      - name: Debug Cache
        run: |
          echo "Gradle cache contents:"
          ls -la ~/.gradle/caches || true
          echo "NDK location:"
          ls -la ${{ github.workspace }}/android-ndk-r26 || true
          echo "Build directory:"
          ls -la **/build || true

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build ${{ matrix.project }}
        run: |
          ./gradlew :${{ matrix.project }}:release \
            -PndkPath=${{ github.workspace }}/android-ndk-r26 \
            -Psigning.gnupg.keyName=${{ secrets.GPG_KEY_ID }} \
            -Psigning.gnupg.passphrase=${{ secrets.GPG_PASSPHRASE }} \
            -Prelease \
            --no-daemon \
            --stacktrace \
            --info \
            --scan

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.project }}-artifacts
          path: ${{ github.workspace }}/build/distributions/*.zip
          if-no-files-found: error

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*.zip
          tag_name: ${{ github.sha }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
